spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_entry.inventory
    username: postgres
    password: artem
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation : true