server:
  port: 8000
  servlet:
    context-path: /order-entry

microservices:
  url:
    prefix: http://
  inventory:
    applicatoin:           ######################################################
      name: inventory      #used instead of host for load balancing restTemplate#
                           ######################################################
    context-path: /inventory
    base-url: ${microservices.url.prefix}${microservices.inventory.applicatoin.name}${microservices.inventory.context-path}
  customer-management:
    application:
      name: customer-management
    context-path: /customer-management
    base-url: ${microservices.url.prefix}${microservices.customer-management.application.name}${microservices.customer-management.context-path}
  catalog:
    application:
      name: catalog
    context-path: /catalog
    base-url: ${microservices.url.prefix}${microservices.catalog.application.name}${microservices.catalog.context-path}

spring:
  application:
    name: processor

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    initial-instance-info-replication-interval-seconds: 1
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
